# Generated by Django 2.2.4 on 2020-12-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Description',
            new_name='description',
        ),
    ]
