# Generated by Django 2.2.4 on 2020-12-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Msg',
        ),
        migrations.RenameModel(
            old_name='MessageManager',
            new_name='MsgManager',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='message_id',
            new_name='msg_id',
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='message',
            new_name='msg',
        ),
    ]
