# Generated by Django 2.2.4 on 2020-12-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20201215_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentManager',
        ),
        migrations.DeleteModel(
            name='MsgManager',
        ),
    ]
