# Generated by Django 2.2.4 on 2020-12-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20201215_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='msg_id',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='user_id',
            new_name='user',
        ),
    ]
